#!/usr/bin/env bash
# Task Summoner one-shot installer.
#
# Idempotent: rerun any time — every step reconciles to the same end state.
# If a step fails, fix the issue and rerun (or use --reset to start clean).
#
# Usage:
#   ./install.sh          # install or re-verify everything
#   ./install.sh --reset  # wipe .venv / node_modules / web_dist first

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

# ---- styling -------------------------------------------------------------
if [ -t 1 ]; then
  BOLD=$'\033[1m'
  CYAN=$'\033[36m'
  GREEN=$'\033[32m'
  YELLOW=$'\033[33m'
  RED=$'\033[31m'
  DIM=$'\033[2m'
  RESET=$'\033[0m'
else
  BOLD=""; CYAN=""; GREEN=""; YELLOW=""; RED=""; DIM=""; RESET=""
fi

step()  { printf "\n${BOLD}${CYAN}==> %s${RESET}\n" "$*"; }
ok()    { printf "   ${GREEN}✓${RESET} %s\n" "$*"; }
info()  { printf "   ${DIM}· %s${RESET}\n" "$*"; }
warn()  { printf "   ${YELLOW}!${RESET} %s\n" "$*"; }
die()   { printf "\n${RED}✗ %s${RESET}\n" "$*" >&2; exit 1; }

on_err() {
  local line=$1
  printf "\n${RED}✗ install.sh failed at line %s${RESET}\n" "$line" >&2
  printf "${YELLOW}  Fix the issue above and rerun ./install.sh — it's idempotent.${RESET}\n" >&2
  printf "${YELLOW}  Or wipe state and start fresh with ./install.sh --reset.${RESET}\n" >&2
}
trap 'on_err $LINENO' ERR

# ---- flags ---------------------------------------------------------------
MODE="install"
for arg in "$@"; do
  case "$arg" in
    --reset) MODE="reset" ;;
    -h|--help)
      sed -n '2,12p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) die "Unknown argument: $arg" ;;
  esac
done

if [ "$MODE" = "reset" ]; then
  step "Resetting install state"
  rm -rf .venv \
         frontend/node_modules \
         backend/src/task_summoner/web_dist \
         backend/src/task_summoner.egg-info \
         task-summoner
  ok "Wiped .venv, node_modules, web_dist, shim"
fi

# ---- preflight -----------------------------------------------------------
step "Preflight"
command -v git >/dev/null || die "git not found."
command -v python3 >/dev/null || die "python3 not found. Install Python 3.11+."

PY_VER=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
PY_MAJOR=${PY_VER%.*}
PY_MINOR=${PY_VER#*.}
if [ "$PY_MAJOR" -lt 3 ] || { [ "$PY_MAJOR" -eq 3 ] && [ "$PY_MINOR" -lt 11 ]; }; then
  die "Python 3.11+ required (found $PY_VER)."
fi
ok "Python $PY_VER"

command -v node >/dev/null || die "Node.js not found. Install v20+ (v22 recommended) from https://nodejs.org."
NODE_MAJOR=$(node -v | sed 's/v//' | cut -d. -f1)
if [ "$NODE_MAJOR" -lt 20 ]; then
  die "Node $NODE_MAJOR found; need v20+."
fi
ok "Node $(node -v)"

# ---- pnpm ----------------------------------------------------------------
step "pnpm"
if ! command -v pnpm >/dev/null; then
  warn "pnpm not found — bootstrapping via corepack"
  if command -v corepack >/dev/null; then
    corepack enable >/dev/null 2>&1 || true
    corepack prepare pnpm@latest --activate >/dev/null
  else
    warn "corepack unavailable, falling back to npm install -g pnpm"
    npm install -g pnpm >/dev/null || die "Could not install pnpm. See https://pnpm.io/installation."
  fi
fi
ok "pnpm $(pnpm -v)"

# ---- backend: venv + editable install -----------------------------------
step "Backend (Python)"
if [ ! -d .venv ]; then
  python3 -m venv .venv
  info "Created .venv"
fi
# shellcheck disable=SC1091
source .venv/bin/activate
python -m pip install --upgrade pip >/dev/null
pip install -e "./backend[dev]" --quiet
deactivate
ok "Editable install ready (task-summoner available inside .venv)"

# ---- frontend: deps + build ---------------------------------------------
step "Frontend (React + TS)"
(
  cd frontend
  if [ -f pnpm-lock.yaml ]; then
    pnpm install --prefer-frozen-lockfile >/dev/null
  else
    pnpm install >/dev/null
  fi
  info "Dependencies installed"
  pnpm build >/dev/null
)
ok "Bundle built → backend/src/task_summoner/web_dist/"

# ---- wrapper shim --------------------------------------------------------
step "Wrapper shim"
cat > task-summoner <<'SHIM'
#!/usr/bin/env bash
# Auto-generated by install.sh. Activates the repo venv and runs task-summoner.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec "$REPO_ROOT/.venv/bin/task-summoner" "$@"
SHIM
chmod +x task-summoner
ok "./task-summoner wrapper ready"

# ---- summary -------------------------------------------------------------
cat <<EOF

${BOLD}${GREEN}✓ Install complete.${RESET}

${BOLD}Next step:${RESET}
  ${CYAN}./task-summoner run${RESET}          — http://localhost:8420 (web setup + dashboard)
  ${CYAN}./task-summoner run --dev${RESET}    — uvicorn + vite hot reload (open :5173)
  ${CYAN}./task-summoner setup${RESET}        — interactive CLI wizard (fallback)

On first run with no config, ${CYAN}/${RESET} auto-redirects to ${CYAN}/setup${RESET} with an amber banner.
Fill the form, Save, and the orchestrator starts without a process restart.

${DIM}Rerun ./install.sh any time — every step is idempotent.
Start fully fresh with ./install.sh --reset.${RESET}
EOF
